### ISSUE TITLE
Paper Item event does not fire on Safari

### ISSUE THREAD

**Issue by pfafman** [Differential/polymer-demo#6]
The paper-item sign out event does not fire in Safari.

FYI: I am seeing a bunch of similar issues with Meteor + Polymer when run on non-chrome browsers.

See: https://github.com/pfafman/meteor-polymer-event-test/issues/1#issuecomment-68000698

You seems to have solved a few with the submit not firing but I think if you stick a plain button somewhere in your app and use a Template event map to catch it you will find it does not fire.  Would like to help clean this up so I and others can use polymer + meteor since it definitely adds some bang.

**Comment by schnie** [comment]
The issue here is a conflict between the way iron-router uses blaze under the hood and polymer.   Internally, blaze delegates all template events to the parent element of a template, but the way iron-router uses the blaze api, the parent element will always be the `body` element.  This works under normal circumstances - all template events are just delegated to `body`, and everything still works as intended.  Polymer (specifically the polyfill, I think) does some work on on the `body` element, and all the event handlers that have been registered there by blaze, via iron-router, get wiped out.

The best solution I've found to cover all circumstances, is to disable `autoStart` and `autoRender` on iron-router and handle it manually.  We need to wait until the dom *and* polymer to be ready, then insert a child element into the `body` and manually start iron-router and tell it to render itself into the new child.  Now, when blaze delegates the event maps out, the parent element will be our new div, which polymer dosn't care about.

See the implementation here 4a8af2bfd5033511d60c261aa150d7cf30a95d6e

**Comment by bangonkali** [comment]
Really look forward for https://github.com/Differential/polymer-demo/issues/6#issuecomment-70098242 to be integrated to https://github.com/ecwyne/meteor-polymer.

**Comment by RobertLowe** [comment]
I wasted way too much time solving this and I found that writing custom events everywhere wasn't a good solution (what about routes with params - it gets annoying).

So, I'm not sure where the root cause is but I'm suspect of the Shadow DOM polyfill/Iron.Location/jQuery.

When a's are clicked they are correctly dispatching an event but the event is already prevented which stops navigation here:

https://github.com/EventedMind/iron-location/blob/master/lib/location.js#L115-L119

A work around for this is:

    Template.globalLayout.helpers
      "click a[href]": (e)->
        href = e.currentTarget.href
        if Iron.Url.isSameOrigin(href, window.location.href)
          Router.go(href)


In addition to this, I also force some styling overrides on paper-item's:

    // fix <a>'s inside a paper item to use the whole area
    paper-item .button-content > a {
      padding: 0.9em 1em;
      margin: -0.9em -1em;
    }
    paper-item @{deep} a {
      padding: 0.9em 1em;
      margin: -0.9em -1em;
    }

As seen in this pull: https://github.com/Polymer/paper-item/pull/17/files
